In this notebook, we will calculate the predicted mortality ratios for 2020.

# **Preliminary steps**

In [1]:
### We import the packages

# To manage dataframes
import numpy as np
import pandas as pd
import math

In [2]:
## We import the previous dataframes

%store -r obs_1_women
%store -r obs_1_men
%store -r obs_2_women
%store -r obs_2_men
%store -r n_2020
%store -r n_2017
%store -r population_2020
%store -r population_2019
%store -r population_2018
%store -r population_2017

# **Functions to transform the dataframes**

In [3]:
# Function f1 to predict mortality ratios
def f1(obs_ratios):
    pred_ratios = pd.DataFrame(obs_ratios.loc[2019, :].copy()).T
    pred_ratios.index = [2020]
    return(pred_ratios)

# Function to get the lower bound of the 95% confidence interval for f1 function
def lower_bound_predicted_ratios_f1(pred_ratios, sex) :
    population = pd.DataFrame(population_2020.loc[sex,:]).T
    y = pd.DataFrame(pred_ratios.loc[2020, :]).T
    for i in range(100):
        x = y.iloc[0,i]-1.96*math.sqrt(n_2020*y.iloc[0,i]*(100000-y.iloc[0,i])/(n_2017*population.iloc[0,i]))
        y.iloc[0,i] = x
    return(y)

# Function to get the upper bound of the 95% confidence interval for f1 function
def upper_bound_predicted_ratios_f1(pred_ratios, sex) :
    population = pd.DataFrame(population_2020.loc[sex,:]).T
    y = pd.DataFrame(pred_ratios.loc[2020, :]).T
    for i in range(100):
        x = y.iloc[0,i]+1.96*math.sqrt(n_2020*y.iloc[0,i]*(100000-y.iloc[0,i])/(n_2017*population.iloc[0,i]))
        y.iloc[0,i] = x
    return(y)

# Function f2 to predict mortality ratios
def f2(obs_ratios):
    pred_ratios = (1/3)*sum(obs_ratios.loc[past_year, :] for past_year in [2017,2018,2019])
    pred_ratios = pd.DataFrame(pred_ratios).T        
    pred_ratios.index = [2020]
    return(pred_ratios)

# Function to get the lower bound of the 95% confidence interval for f2 function
def lower_bound_predicted_ratios_f2(pred_ratios, obs_ratios, sex) :
    population = pd.DataFrame(population_2020.loc[sex,:]).T
    y = pd.DataFrame(pred_ratios.loc[2020, :]).T
    ratios_2017 = pd.DataFrame(obs_ratios.loc[2017,:]).T
    ratios_2018 = pd.DataFrame(obs_ratios.loc[2018,:]).T
    ratios_2019 = pd.DataFrame(obs_ratios.loc[2019,:]).T
    populations = pd.concat([population_2017.loc[sex,:],population_2018.loc[sex,:],population_2019.loc[sex,:]], axis =1).T
    for i in range(100):
        a = ratios_2017.iloc[0,i]*(100000-ratios_2017.iloc[0,i])/(populations.iloc[0,i])
        b = ratios_2018.iloc[0,i]*(100000-ratios_2018.iloc[0,i])/(populations.iloc[1,i])
        c = ratios_2019.iloc[0,i]*(100000-ratios_2019.iloc[0,i])/(populations.iloc[2,i])
        h = y.iloc[0,i]-1.96*math.sqrt((a+b+c)/9)
        y.iloc[0,i] = h
    return(y)

# Function to get the upper bound of the 95% confidence interval for f2 function
def upper_bound_predicted_ratios_f2(pred_ratios, obs_ratios, sex) :
    population = pd.DataFrame(population_2020.loc[sex,:]).T
    y = pd.DataFrame(pred_ratios.loc[2020, :]).T
    ratios_2017 = pd.DataFrame(obs_ratios.loc[2017,:]).T
    ratios_2018 = pd.DataFrame(obs_ratios.loc[2018,:]).T
    ratios_2019 = pd.DataFrame(obs_ratios.loc[2019,:]).T
    populations = pd.concat([population_2017.loc[sex,:],population_2018.loc[sex,:],population_2019.loc[sex,:]], axis =1).T
    for i in range(100):
        a = ratios_2017.iloc[0,i]*(100000-ratios_2017.iloc[0,i])/(populations.iloc[0,i])
        b = ratios_2018.iloc[0,i]*(100000-ratios_2018.iloc[0,i])/(populations.iloc[1,i])
        c = ratios_2019.iloc[0,i]*(100000-ratios_2019.iloc[0,i])/(populations.iloc[2,i])
        h = y.iloc[0,i]+1.96*math.sqrt((a+b+c)/9)
        y.iloc[0,i] = h
    return(y)

# **First database**

In [4]:
# We predict mortality ratios for 2020

pred_1_women_f1 = f1(obs_1_women)
pred_1_men_f1 = f1(obs_1_men)
pred_1_women_f2 = f2(obs_1_women)
pred_1_men_f2 = f2(obs_1_men)
pred_1_women_f2

,0 an,1 an,2 ans,3 ans,4 ans,5 ans,6 ans,7 ans,8 ans,9 ans,...,111 ans,112 ans,113 ans,114 ans,115 ans,116 ans,117 ans,118 ans,119 ans,120 ans
2020,353.333333,25.666667,14.333333,11.0,8.666667,8.0,8.0,5.666667,5.333333,6.333333,...,37807.0,37807.0,37807.0,37807.0,37807.0,37807.0,37807.0,37807.0,37807.0,38358.666667

In [5]:
# We calculate lower and upper bounds of the 95% confidence interval for 2020

pred_1_women_f1_lower = lower_bound_predicted_ratios_f1(pred_1_women_f1, 'Women')
pred_1_women_f1_upper = upper_bound_predicted_ratios_f1(pred_1_women_f1, 'Women')
pred_1_men_f1_lower = lower_bound_predicted_ratios_f1(pred_1_men_f1, 'Men')
pred_1_men_f1_upper = lower_bound_predicted_ratios_f1(pred_1_men_f1, 'Men')

pred_1_women_f2_lower = lower_bound_predicted_ratios_f2(pred_1_women_f2, obs_1_women, 'Women')
pred_1_women_f2_upper = upper_bound_predicted_ratios_f2(pred_1_women_f2, obs_1_women, 'Women')
pred_1_men_f2_lower = lower_bound_predicted_ratios_f2(pred_1_men_f2, obs_1_men, 'Men')
pred_1_men_f2_upper = lower_bound_predicted_ratios_f2(pred_1_men_f2, obs_1_men, 'Men')

pred_1_women_f2_lower

,0 an,1 an,2 ans,3 ans,4 ans,5 ans,6 ans,7 ans,8 ans,9 ans,...,111 ans,112 ans,113 ans,114 ans,115 ans,116 ans,117 ans,118 ans,119 ans,120 ans
2020,341.796457,22.590545,12.066574,9.039063,6.946296,6.359242,6.375659,4.305219,4.016678,4.896646,...,37807.0,37807.0,37807.0,37807.0,37807.0,37807.0,37807.0,37807.0,37807.0,38358.666667

# **Second database**

In [6]:
# We predict mortality ratios for 2020

pred_2_women_f1 = f1(obs_2_women)
pred_2_men_f1 = f1(obs_2_men)
pred_2_women_f2 = f2(obs_2_women)
pred_2_men_f2 = f2(obs_2_men)
pred_2_women_f2

,0 an,1 an,2 ans,3 ans,4 ans,5 ans,6 ans,7 ans,8 ans,9 ans,...,91 ans,92 ans,93 ans,94 ans,95 ans,96 ans,97 ans,98 ans,99 ans,100 ans
2020,318.333333,53.0,18.333333,13.333333,10.0,8.666667,8.333333,6.333333,5.0,6.0,...,11737.666667,13338.0,15186.333333,17120.666667,19244.666667,21262.333333,23461.666667,25808.333333,28362.333333,30909.666667

In [7]:
# We calculate lower and upper bounds of the 95% confidence interval for 2020

pred_2_women_f1_lower = lower_bound_predicted_ratios_f1(pred_2_women_f1, 'Women')
pred_2_women_f1_upper = upper_bound_predicted_ratios_f1(pred_2_women_f1, 'Women')
pred_2_men_f1_lower = lower_bound_predicted_ratios_f1(pred_2_men_f1, 'Men')
pred_2_men_f1_upper = lower_bound_predicted_ratios_f1(pred_2_men_f1, 'Men')

pred_2_women_f2_lower = lower_bound_predicted_ratios_f2(pred_2_women_f2, obs_2_women, 'Women')
pred_2_women_f2_upper = upper_bound_predicted_ratios_f2(pred_2_women_f2, obs_2_women, 'Women')
pred_2_men_f2_lower = lower_bound_predicted_ratios_f2(pred_2_men_f2, obs_2_men, 'Men')
pred_2_men_f2_upper = lower_bound_predicted_ratios_f2(pred_2_men_f2, obs_2_men, 'Men')

pred_2_women_f2_lower

,0 an,1 an,2 ans,3 ans,4 ans,5 ans,6 ans,7 ans,8 ans,9 ans,...,91 ans,92 ans,93 ans,94 ans,95 ans,96 ans,97 ans,98 ans,99 ans,100 ans
2020,307.380256,48.582718,15.76805,11.173002,8.151887,6.958074,6.674334,4.895057,3.725246,4.601908,...,11625.871109,13210.038019,15038.027406,16948.364097,19043.325951,21024.773027,23148.486108,25383.225971,27781.769456,30909.666667

# **Saving our dataframes**

In [8]:
%store pred_1_women_f1
%store pred_1_women_f1_lower
%store pred_1_women_f1_upper
%store pred_1_men_f1
%store pred_1_men_f1_lower
%store pred_1_men_f1_upper

%store pred_1_women_f2
%store pred_1_women_f2_lower
%store pred_1_women_f2_upper
%store pred_1_men_f2
%store pred_1_men_f2_lower
%store pred_1_men_f2_upper

%store pred_2_women_f1
%store pred_2_women_f1_lower
%store pred_2_women_f1_upper
%store pred_2_men_f1
%store pred_2_men_f1_lower
%store pred_2_men_f1_upper

%store pred_2_women_f2
%store pred_2_women_f2_lower
%store pred_2_women_f2_upper
%store pred_2_men_f2
%store pred_2_men_f2_lower
%store pred_2_men_f2_upper

Stored 'pred_1_women_f1' (DataFrame)
Stored 'pred_1_women_f1_lower' (DataFrame)
Stored 'pred_1_women_f1_upper' (DataFrame)
Stored 'pred_1_men_f1' (DataFrame)
Stored 'pred_1_men_f1_lower' (DataFrame)
Stored 'pred_1_men_f1_upper' (DataFrame)
Stored 'pred_1_women_f2' (DataFrame)
Stored 'pred_1_women_f2_lower' (DataFrame)
Stored 'pred_1_women_f2_upper' (DataFrame)
Stored 'pred_1_men_f2' (DataFrame)
Stored 'pred_1_men_f2_lower' (DataFrame)
Stored 'pred_1_men_f2_upper' (DataFrame)
Stored 'pred_2_women_f1' (DataFrame)
Stored 'pred_2_women_f1_lower' (DataFrame)
Stored 'pred_2_women_f1_upper' (DataFrame)
Stored 'pred_2_men_f1' (DataFrame)
Stored 'pred_2_men_f1_lower' (DataFrame)
Stored 'pred_2_men_f1_upper' (DataFrame)
Stored 'pred_2_women_f2' (DataFrame)
Stored 'pred_2_women_f2_lower' (DataFrame)
Stored 'pred_2_women_f2_upper' (DataFrame)
Stored 'pred_2_men_f2' (DataFrame)
Stored 'pred_2_men_f2_lower' (DataFrame)
Stored 'pred_2_men_f2_upper' (DataFrame)